version: "3"
services:
    web:
        build:
            context: web
            args:
                - SLACK_CLIENT_ID=${SLACK_CLIENT_ID}
                - SLACK_TEAM=${SLACK_TEAM}
                - SERVER_URL=${SERVER_URL}
        ports:
            - "3000:3000"

    nginx:
        image: nginx
        ports:
            - "80:80"
        environment:
            - NGINX_HOST
        volumes:
            - ./nginx/nginx.conf:/tmp/nginx.conf:ro
        command: /bin/bash -c "envsubst '$${NGINX_HOST}'< /tmp/nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
        depends_on:
            - web

    app:
        build: app
        volumes:
            - ./app:/src
        ports:
            - "5000:5000"
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: postgres
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD

    elasticsearch:
        build: elasticsearch
        volumes:
            - es-data:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - ES_JAVA_OPTS=-Xms256m -Xmx256m

    es-python:
        build: es-python
        volumes:
            - ./es-python:/src
        environment:
            - SLACK_API_TOKEN


volumes:
    db-data:
    es-data:
