version: "3"
services:
    web:
        build:
            context: web
            args:
                - SLACK_CLIENT_ID=${SLACK_CLIENT_ID}
                - SLACK_TEAM=${SLACK_TEAM}
                - SERVER_URL=${SERVER_URL}
        ports:
            - "80:3000"
        depends_on:
            - app

    app:
        build: app
        volumes:
            - ./app:/src
        ports:
            - "5000:5000"
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: postgres
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD
    
    elasticsearch:
        build: elasticsearch
        volumes:
            - es-data:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - ES_JAVA_OPTS=-Xms256m -Xmx256m

    es-python:
        build: es-python
        volumes:
            - ./es-python:/src
        environment:
            - SLACK_API_TOKEN


volumes:
    db-data:
    es-data:
