version: "3"
services:
    web:
        build:
            context: web
            args:
                - SLACK_CLIENT_ID=${SLACK_CLIENT_ID}
                - SLACK_TEAM=${SLACK_TEAM}
                - SERVER_URL=${SERVER_URL}
        ports:
            - "80:3000"

    app:
        build: app
        volumes:
            - ./app:/src
        ports:
            - "5000:5000"
        env_file:
            - .env

    db:
        image: postgres
        restart: always
        volumes:
            - db-data/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD

volumes:
    db-data:
